spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/study_cafe
    username: tester
    password: 1234
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass

