spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    url: ENC(ZNVgCDlDyGLAiVuOFyKbuh6k948NL2Oxo/Lxvi1+enSsVsGV8GTtDCRU12qBjYKkM2HkzKhFjjA=)
    username: ENC(wxKpNxPnLSHl/hjg0l/9qg==)
    password: ENC(RyRfn8jiIVAd0gfNsDxOzw==)
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  mail :
    host : smtp.gmail.com
    port : 587
    username : ENC(V95RhsiwpZy2VAHwnQoA1LR82TERj5chwOoZhj75Z+8=)
    password : ENC(bo69HNq6bzOND0a7FtCy2Tp+AZ6Z8075)
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor